### ISSUE TITLE
Create a package for bower

### ISSUE THREAD

**Issue by akermabon** [stritti/log4js#1]
Hello,
Could you create a package so we can use this great library with bower ? 
Thank you.

**Comment by dimalev** [comment]
i believe 1.0.0 is broken in bower :(
Log4js variable is broken on line 145
anybody saw this issue ?

**Comment by stritti** [comment]
This was solved in #8  but not jet released to bower.

**Comment by sammarland** [comment]
Any update on this? When are you targeting this for release in bower?

**Comment by stritti** [comment]
There is currently a beta of new version: https://github.com/stritti/log4js/releases/tag/v2.0.0Beta1 
Will be soon in bower.
