### ISSUE TITLE
I am new to this and trying to add logging in my react appplication using webpack. But it fails at runtime,

### ISSUE THREAD

**Issue by KalpanaPagariya** [stritti/log4js#20]
Below is the exception:
Uncaught TypeError: Cannot read property 'write' of undefined
    at exports.Console.Console.log (http://localhost:8080/public/bundle.js:110094:19)
    at transportLog (http://localhost:8080/public/bundle.js:109429:15)
    at http://localhost:8080/public/bundle.js:45186:13
    at _each (http://localhost:8080/public/bundle.js:45086:9)
    at Object.async.each (http://localhost:8080/public/bundle.js:45185:9)
    at exports.Logger.Logger.log (http://localhost:8080/public/bundle.js:109441:9)
    at Object.winston.(anonymous function) [as log] (http://localhost:8080/public/bundle.js:28305:34)
    at Object.defineProperty.value (http://localhost:8080/public/bundle.js:57848:9)
    at __webpack_require__ (http://localhost:8080/public/bundle.js:20:30)
    at Object.<anonymous> (http://localhost:8080/public/bundle.js:58069:23)

**Server.js file:**
var path = require('path');
var express = require('express');
var webpack = require('webpack');
var config = require('./webpack.config.dev');

var app = express();
var compiler = webpack(config);
var log4js = require('log4js');

var logger= require('./logger.js');
var log=logger.LOG;

app.use(require('webpack-dev-middleware')(compiler, {
  noInfo: true,
  publicPath: config.output.publicPath
}));

app.use(express.static(__dirname))

app.get('*', function(req, res) {
  log.debug('Hi');
  res.sendFile(path.join(__dirname, '/index.html'));
});

app.use(log4js.connectLogger(log, { level: log4js.levels.DEBUG }));

app.listen(8080, 'localhost', function(err) {
  log.debug('Hi');
  if (err) {
    console.log(err);
    return;
  }

  console.log('Listening at http://localhost:8080');
});

**webpack config file:**

var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
  devtool: 'source-map',
  entry: [
  //  'webpack-dev-server/client?http://localhost:8080/', // WebpackDevServer host and port
  //   'webpack/hot/only-dev-server', // "only" prevents reload on syntax errors
    './src/com/avaya/components/index'],
  output: {
    filename: 'bundle.js',
    path: path.join(__dirname, '/public'),
    publicPath: 'http://localhost:8080/public/'
  },
  module: {
    loaders: [
      { test: /\.js$/, loaders: ['babel-loader'] ,  exclude: /node_modules/},
     {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
            fallback: 'style-loader',
            use: [ 
              { loader: 'css-loader', options: { minimize: true } } 
            ]
        })
      },
     
       {
        test: /\.(png|jpg|)$/,
        loader: 'url-loader?limit=200000'
      },
      {
        test: /\.(jpg|png)$/,
      loader: "url-loader?mimetype=image/png"
      },
        {
          test: /\.(woff|woff2)$/,
          // Inline small woff files and output them below font/.
          // Set mimetype just in case.
          loader: 'url-loader',
          options: {
            name: 'fonts/[hash].[ext]',
            limit: 5000,
            mimetype: 'application/font-woff'
          },
         // include: PATHS.fonts
        },
        {
          test: /\.ttf$|\.eot$|\.svg$/,
          loader: 'file-loader',
          options: {
            name: 'fonts/[hash].[ext]'
          },
          //include: PATHS.fonts
        },
        
     
        
    ]
  },
node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },
  plugins: [
   new ExtractTextPlugin('style.css'),
   //new webpack.HotModuleReplacementPlugin()
   
 ]

};

**Comment by KalpanaPagariya** [comment]
And also build succeded with so many errors:
RROR in ./~/streamroller/lib/RollingFileStream.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\pagariyak\Project\UI_upgrade\8.0\core\cc\react-cc-components\node_modules\streamroller\lib'
 @ ./~/streamroller/lib/RollingFileStream.js 6:18-42
 @ ./~/streamroller/lib/index.js
 @ ./~/log4js/lib/appenders/dateFile.js
 @ ./~/log4js/lib/appenders ^\.\/.*$
 @ ./~/log4js/lib/log4js.js
 @ ./src/com/avaya/components/avayaTable/container/AvayaTableDemo.js
 @ ./src/com/avaya/components/demoComponent/PageLayout.js
 @ ./src/com/avaya/components/index.js
 @ multi ./src/com/avaya/components/index

ERROR in ./~/log4js/lib/appenders/clustered.js
Module not found: Error: Can't resolve 'cluster' in 'C:\Users\pagariyak\Project\UI_upgrade\8.0\core\cc\react-cc-components\node_modules\log4js\lib\appenders'
 @ ./~/log4js/lib/appenders/clustered.js 3:14-32
 @ ./~/log4js/lib/appenders ^\.\/.*$
 @ ./~/log4js/lib/log4js.js
 @ ./src/com/avaya/components/avayaTable/container/AvayaTableDemo.js
 @ ./src/com/avaya/components/demoComponent/PageLayout.js
 @ ./src/com/avaya/components/index.js
 @ multi ./src/com/avaya/components/index

ERROR in ./~/log4js/lib/appenders/gelf.js
Module not found: Error: Can't resolve 'dgram' in 'C:\Users\pagariyak\Project\UI_upgrade\8.0\core\cc\react-cc-components\node_modules\log4js\lib\appenders'
 @ ./~/log4js/lib/appenders/gelf.js 5:12-28
 @ ./~/log4js/lib/appenders ^\.\/.*$
 @ ./~/log4js/lib/log4js.js
 @ ./src/com/avaya/components/avayaTable/container/AvayaTableDemo.js
 @ ./src/com/avaya/components/demoComponent/PageLayout.js
 @ ./src/com/avaya/components/index.js
 @ multi ./src/com/avaya/components/index

ERROR in ./~/log4js/lib/appenders/hipchat.js
Module not found: Error: Can't resolve 'hipchat-notifier' in 'C:\Users\pagariyak\Project\UI_upgrade\8.0\core\cc\react-cc-components\node_modules\log4js\lib\appenders'
 @ ./~/log4js/lib/appenders/hipchat.js 3:14-41
 @ ./~/log4js/lib/appenders ^\.\/.*$
 @ ./~/log4js/lib/log4js.js
 @ ./src/com/avaya/components/avayaTable/container/AvayaTableDemo.js
 @ ./src/com/avaya/components/demoComponent/PageLayout.js
 @ ./src/com/avaya/components/index.js
 @ multi ./src/com/avaya/components/index

**Comment by stritti** [comment]
I think you are using node-forge of this lib: https://github.com/log4js-node/log4js-node

**Comment by moffsugita** [comment]
```
./node_modules/log4js/lib/clustering.js
Module not found: Can't resolve 'cluster' in '/Users/username/Documents/moff_day_care_react_dashboard_BACK/node_modules/log4js/lib'
```

**Comment by stritti** [comment]
@moffsugita I think you mixed there some other stuff. This version of log4js has currently no npm package.
