### ISSUE TITLE
Log4js bug

### ISSUE THREAD

**Issue by TheWhiteLow** [stritti/log4js#22]
Hi,
I have a bug in my method of js

code:
Var logger = log4js.getLogger ();
log4js.configure ({
Appenders: [
{Type: 'console'},
{Type: 'file', filename: 'logs / bot_' + process.argv [2] + '. Log'}
]
});
error:
/home/bot/node_modules/log4js/lib/configuration.js:38
                  Throw new Error (
                  ^

Error: Problem with log4js configuration: ({appenders:
   [{Type: 'console'},
     {Type: 'file', filename: 'logs / bot_0.log'}]}) - must have a property "appenders" of type object.
    At tests.forEach (/home/bot/node_modules/log4js/lib/configuration.js:38:11)
    At Array.forEach (<anonymous>)
    At Configuration.throwExceptionIf (/home/bot/node_modules/log4js/lib/configuration.js:36:11)
    At new Configuration (/home/bot/node_modules/log4js/lib/configuration.js:199:10)
    At Object.configure (/home/bot/node_modules/log4js/lib/log4js.js:195:12)
    At Object. <Anonymous> (/home/bot/bot.js:20:8)
    At Module._compile (module.js: 573: 30)
    At Object.Module._extensions..js (module.js: 584: 10)
    At Module.load (module.js: 507: 32)
    At tryModuleLoad (module.js: 470: 12)

**Comment by stritti** [comment]
I think you are using the node forge: https://github.com/log4js-node/log4js-node
