### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by ltdeta** [stritti/log4js#31]
Is this project still active or dead?
If so (I hope not), does anyone know an alternative?

**Comment by stritti** [comment]
@ltdeta the project is not dead, but very low prio. Contributions (e.g. Pull Requests) are very welcome.

**Comment by ltdeta** [comment]
Hello stritti,
I can understand that, but should basic issues not be corrected in a timely manner? Like this topic #29 
Otherwise, you may turn away frustrated from this project, although it is a good thing.

Why do not you alternatively provide a compiled version. That you have to deal only with Grunt does not make the whole easier

**Comment by stritti** [comment]
Hello @ltdeta,

you are right. i had added combiled version, but it had not worked any more. Thanks for the hint. I investigated and now it is reactivated to have downloadable minified version of Log4js.
